version: '2'

services:
  ghost:
    image: ghost:3
    ports:
      - 5001:2368
    volumes:
      - ./data/ghost:/var/lib/ghost/content
    labels:
      - "traefik.http.routers.ghost.rule=Host(`blog.myserver.test`)"

  dokuwiki:
    image: bitnami/dokuwiki:0
    ports:
      - 5002:80
    volumes:
      - ./data/dokuwiki:/bitnami
    labels:
      - "traefik.http.routers.dokuwiki.rule=Host(`wiki.myserver.test`)"

  traefik:
    container_name: traefik
    image: traefik:2.0
    ports:
      - 5003:8080 # webUI
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml
